name: Deploy static content to Pages

on:
  push:
    branches: ["main"] # nebo "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "./visualization-app/package-lock.json"

      - name: Install dependencies
        run: |
          cd visualization-app
          npm install

      - name: Build
        run: |
          cd visualization-app
          npm run build # Ujisti se, že v package.json máš "vite build"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./visualization-app/dist" # GitHub nepotřebuje složku "public", stačí mu "dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
